-- Seed katalogu služeb Bicom Písek (ceny z cenové analýzy 2024–2025).
-- Ceny jsou orientační „od"; vždy přes právní filtr (03_GEO_AEO/03) — žádné léčebné sliby.
INSERT OR REPLACE INTO services (slug,name,segment,short_desc,long_desc,price_from,sessions_typ,active) VALUES
('vstupni-diagnostika','Vstupní diagnostika a plán','vsechny',
 'Úvodní zmapování zátěže organismu a sestavení individuálního plánu.',
 'Šetrné, neinvazivní vstupní sezení (cca 60 min): zmapování zátěže a sestavení individuálního plánu péče. Komplementární přístup, doplněk klasické medicíny.',
 1200,'1 sezení (60 min)',1),
('terapeuticke-sezeni','Terapeutické / kontrolní sezení','vsechny',
 'Navazující sezení dle individuálního plánu.',
 'Standardní 60min sezení navazující na vstupní plán. Počet se liší podle individuální potřeby.',
 1200,'dle plánu',1),
('odvykani-koureni','Odvykání kouření a vapingu','kouraci',
 'Šetrná podpora při odvykání kouření i vapingu, vč. podpůrného čipu.',
 'Program podpory při odvykání kouření a vapingu (cca 50–60 min, vč. podpůrného čipu). Pragmatická volba pro úsporu i klid. Výsledky se u jednotlivců liší.',
 1500,'obvykle 1–3 sezení',1),
('alergie-deti','Testování a podpora při alergiích u dětí','matky_deti',
 'Neinvazivní, bezbolestné testování alergenů a šetrná podpora.',
 'Bezbolestné neinvazivní testování zátěže (pyly, potraviny — mléko, lepek) a šetrná podpora při atopickém ekzému a alergiích. Komplementárně k péči pediatra. Pro děti sleva 20 %.',
 500,'individuální plán',1),
('stres-vyhoreni','Podpora při stresu a vyhoření','zeny',
 'Klidná podpora při chronickém stresu, vyhoření a poruchách spánku.',
 'Empatická podpora při chronickém stresu, vyhoření a poruchách spánku. Klidné útočiště pro přetížené ženy i profesionály. Doplněk, ne náhrada lékařské péče.',
 1200,'obvykle 3–6 sezení',1),
('bolesti-zad','Podpora pohybového aparátu','prumysl_zamestnanci',
 'Úleva při potížích z jednostranné a sedavé zátěže.',
 'Podpora při potížích pohybového aparátu z jednostranné fyzické či sedavé zátěže (typické pro průmysl i IT). Podpora regenerace, nenahrazuje rehabilitaci.',
 1200,'obvykle 2–4 sezení',1),
('testovani-alergenu','Testování alergenů','vsechny',
 'Neinvazivní orientační testování zátěže organismu.',
 'Neinvazivní orientační testování zátěže organismu (cca 30 min).',
 500,'1 sezení (30 min)',1),
('balicek-5','Balíček 5 sezení','vsechny',
 'Zvýhodněný balíček 5 sezení se slevou 10–15 %.',
 'Zvýhodněný balíček 5 sezení (sleva 10–15 %) — snižuje finanční bariéru, jasný plán bez skrytých poplatků.',
 5400,'5 sezení',1);
